// <auto-generated />
using System;
using GymTrack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymTrack.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260421185533_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ExercicioFichaTreino", b =>
                {
                    b.Property<int>("ExerciciosId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FichasTreinoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ExerciciosId", "FichasTreinoId");

                    b.HasIndex("FichasTreinoId");

                    b.ToTable("ExercicioFichaTreino");
                });

            modelBuilder.Entity("GymTrack.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataMatricula")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("GymTrack.Models.Exercicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GrupoMuscular")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Exercicios");
                });

            modelBuilder.Entity("GymTrack.Models.FichaTreino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlunoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlanoTreinoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("PlanoTreinoId");

                    b.ToTable("FichasTreino");
                });

            modelBuilder.Entity("GymTrack.Models.PlanoTreino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PlanosTreino");
                });

            modelBuilder.Entity("ExercicioFichaTreino", b =>
                {
                    b.HasOne("GymTrack.Models.Exercicio", null)
                        .WithMany()
                        .HasForeignKey("ExerciciosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymTrack.Models.FichaTreino", null)
                        .WithMany()
                        .HasForeignKey("FichasTreinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymTrack.Models.FichaTreino", b =>
                {
                    b.HasOne("GymTrack.Models.Aluno", "Aluno")
                        .WithMany("FichasTreino")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymTrack.Models.PlanoTreino", "PlanoTreino")
                        .WithMany("FichasTreino")
                        .HasForeignKey("PlanoTreinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("PlanoTreino");
                });

            modelBuilder.Entity("GymTrack.Models.Aluno", b =>
                {
                    b.Navigation("FichasTreino");
                });

            modelBuilder.Entity("GymTrack.Models.PlanoTreino", b =>
                {
                    b.Navigation("FichasTreino");
                });
#pragma warning restore 612, 618
        }
    }
}
